export interface Stuff{
  userId : string;
  stuffName : string;
  classId : string;
  helmetId : string;
  chestplateId : string;
  gantletId : string;
  bootsId : string;
  talismansIds : Array<string>;
  weaponsId : Array<string>;
  vigor : number;
  esprit : number;
  endurance : number;
  force : number;
  dexterite : number;
  intelligence : number;
  foi : number;
  esoterisme : number;
  level : number;
}
